### ISSUE TITLE
fail to get follower info

### ISSUE THREAD

**Issue by ze42** [streamersonglist/issue-tracking#17]
Getting some `Requests are only enabled for: followers, subscribers` on a stream, thought I have been following for years.

Might be related to "recent" twitch API change.

I know there used to be a page where you could check follow-age of anyone for any channel, and now is restricted to channel you are mods...

Note: If that repo is not used anymore, or if there are some config to be done on streamer side, please let me know where to find it... (not sure where to find doc to start with anyway)

**Comment by travtarr** [comment]
The streamer will need to re-authorize StreamerSonglist with Twitch to obtain the new scope for the new follower enpoint.

They can do that on the Settings -> Basic page at the bottom.

**Comment by ze42** [comment]
Thanks. Worked fine. (took some time to ask them to do it, and find the exact menu, but it worked!)
